version: '3.8'
services:
  parser:
    container_name: parser
    build:
      context: parser
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - web
    depends_on:
      - chrome
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2g


networks:
  web:
    driver:  bridge
