version: '3.8'
services:
  parser:
    container_name: parser
    hostname: parser
    build:
      context: parser
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - web
    depends_on:
      - chrome
  tg_bot:
    container_name: tgbot
    hostname: tgbot
    build:
      context: tgbot
      dockerfile: Dockerfile
    ports:
      - "9095:9095"
    networks:
      - web
    volumes:
      - ./tgbot/.docker-temp:/etc/tgbot
  analyzer:
    container_name: analyzer
    build:
      context: analytics
      dockerfile: Dockerfile
    networks:
      - web
    depends_on:
      - parser
      - tg_bot
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    networks:
      - web
    privileged: true
    shm_size: 2g


networks:
  web:
    driver:  bridge
